version: '3'

services:

  api-gateway:
    build:
      context: ../
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"

  user-service:
    build:
      context: ../
      dockerfile: user-service/Dockerfile
    container_name: user-service
    ports:
      - "8071:8071"