version: '3'

services:

  api-gateway:
    build:
      context: ../
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8080"
    depends_on: [zookeeper, kafka]

  user-service:
    build:
      context: ../
      dockerfile: user-service/Dockerfile
    container_name: user-service
    ports:
      - "${USER_SERVICE_PORT}:8081"
    depends_on: [zookeeper, kafka]